# This is a basic workflow to help you get started with Actions

name: approve test

on:
  workflow_dispatch:

jobs:
  call1:
    uses: timeleap-takaaki/github-actions-sandbox/.github/workflows/hello_world_call.yml@main
    with:
      your_name: Bob

  call2:
    uses: timeleap-takaaki/github-actions-sandbox/.github/workflows/hello_world_call.yml@main
    with:
      your_name: Jon

  call3:
    uses: timeleap-takaaki/github-actions-sandbox/.github/workflows/hello_world_call.yml@main
    with:
      your_name: Mary