# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
  call:
    uses: timeleap-takaaki/github-actions-sandbox/.github/workflows/hello_world_call.yml@main
