# This is a basic workflow to help you get started with Actions

name: Environment Secret test

on:
  workflow_dispatch:

jobs:
  call1:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: timeleap-takaaki/github-actions-sandbox/.github/workflows/hello_world_call.yml@main
        with:
          your_name: Bob
          gh_env: test
      - uses: timeleap-takaaki/github-actions-sandbox/.github/workflows/hello_world_call.yml@main
        with:
          your_name: Jon
          gh_env: test_2