---
name: Hello World Call Workflow

on:
  workflow_call:
    inputs:
      your_name:
        description: "Your Name"
        type: string
        required: true

jobs:
  
  hello:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world! ${{ inputs.your_name }}
