---
name: Hello World Call Workflow

on:
  workflow_call:
    inputs:
      gh_env:
        description: 'GitHub Environment'
        type: string
        required: true
      your_name:
        description: "Your Name"
        type: string
        required: true

jobs:
  
  hello:
    runs-on: ubuntu-latest
    environment: ${{ inputs.gh_env }}
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world! ${{ inputs.your_name }}

      - run: echo "token = ${{ env.TOKEN }}"